package pereira.agnaldo.downloadwebpage;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'agnaldo' at '15/12/16 12:01' with Gradle 3.0
 *
 * @author agnaldo, @date 15/12/16 12:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
