import org.junit.Test;

import pereira.agnaldo.downloadwebpage.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'agnaldo' at '15/12/16 12:01' with Gradle 3.0
 *
 * @author agnaldo, @date 15/12/16 12:01
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
